name: Run html_proofer

on: [pull-request]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby & bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Build jekyll site
      run: |
        bundle exec jekyll build
    - name: Run html linter
      run: |
        bundle exec rake html_proofer
